name: Container Build
# This workflow triggers when a new tag is pushed to the repository.
# If everything goes right, it should be the last workflow that fires.

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  container-build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/riking-AutoDelete
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
             "org.opencontainers.image.description=AutoDelete bot for Discord"

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v2
    
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_COMMIT=${{ github.sha }}  
            SEMVER=${{ steps.meta.outputs.version }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}